server:
  port: '@server.port@'
  rest:
    port: 8080
    endpoint: '@server.rest.endpoint@'

management:
  security:
    flag: false
  server:
    port: '@management.port@'
  metrics:
    tags:
      application: '@project.name@'
    export:
      prometheus:
        enabled: true
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

spring:
  application:
    name: '@project.name@'
  output:
    ansi:
      enabled: always
info:
  version: '@project.version@'
  stage: dev

adapter:
  url: https://change_it
  merchantRedirectUrl: https://change_it
  notificationUrl: https://change_it
  finishRedirectUrl: https://checkout.empayre.com/v1/finish-interaction.html
  tag-prefix: PMB-NB-
  redirectTimeout: 60000

error-mapping:
  file: classpath:fixture/errors.json
  patternReason: "'%s' - '%s'" # 'code' - 'description'

hellgate:
  client:
    adapter:
      url: http://localhost:8023/v1/proxyhost/provider
      networkTimeout: 30000

restTemplate:
  requestTimeout: 60000
  poolTimeout: 10000
  connectionTimeout: 10000
  maxTotalPooling: 200
  defaultMaxPerRoute: 200